### PR TITLE
build system: use system version of UTF8-CPP if present

### PR DESCRIPTION
**Pull request by rathann**
UTF8-CPP is packaged in Fedora. This patch adds the option to use the system version if available.

### CODE REVIEW

**Comment by rathann** [comment]
Check updated. Please see if it's acceptable now.

**Comment by mbunkus** [comment]
Looks fine, thanks.

**Comment by mbunkus** [comment]
…and your patch breaks systems on which `ut8.h` is not available – because you didn't modify `build-config.in`. I should have checked that…

**Comment by rathann** [comment]
Sorry about that. I should've checked, too. Will you fix it yourself or shall I?

**Comment by rathann** [comment]
Ah, I see you've fixed it already. Thanks.

**Comment by mbunkus** [comment]
Yeah, I've fixed it in the next commit. Otherwise my [BuildBot](https://www.bunkus.org/buildbot/console) would have continued complaining, and that does get annoying ;)

**Pull request merged**
