### PR TITLE
Update of Spanish and Basque

### PR DESCRIPTION
**Pull request by egoitzro**
Hi, I made update of this two language po files and I wish they were in the next update of application

### CODE REVIEW

**Comment by mbunkus** [comment]
Thanks. You had two instances of wrong format strings that I've fixed in an additional commit, 06f27dff31f66daa9fdaf06600c2cfee1e848b27.

A note about the commit messages: I usually only include »update list of translatable strings« for commits that actually ran »drake translations:update:applications«, not for commits which only add/change the translations themselves.

**Comment by egoitzro** [comment]
apologize if I have committed a fault, but is the first time you used this system, I have done other translations but all through transifex and / or if you use Linux distribution with some explanation by the committers.

Thank you.

**Comment by mbunkus** [comment]
No problem at all. I wasn't complaining, only giving you a heads-up.

MKVToolNix uses two different formatting systems/libraries: Qt for the GUI and Boost::Format for everything else. Boost::Format uses the style that looks like this: `%1%` or `%|1$04x|`. Qt uses the similar-looking `%1` (no trailing `%`). So it's easy to make mistakes here; it happens to me, too.

There's a build target that verifies the formatting strings: `./drake translations:verify-format-strings`. This is how I saw the two small problems in your translations.

**Comment by egoitzro** [comment]
Ok, I will use the next time I make a translation.

Thanks

**Pull request merged**
