### PR TITLE
Support prores

### PR DESCRIPTION
**Pull request by chenchao1983**
Dear Colleagues,
I enabled mkvmerge to support remuxing prores video into mkv containers in this request. Please have a look and let me know your comments.

best regards,
Chao Chen

### CODE REVIEW

**Comment by mbunkus** [comment]
Thanks for the pull request. I have a couple of remarks/questions.

The FourCC:

Why are you storing the FourCC in CodecPrivate? I've just looked through ffmpeg's decoder code for ProRes and it doesn't seem use the FourCC at all; in fact the FourCC stored in an MP4 file is not passed to the ProRes decoder.

The packetizer:

Your implementation of the packetizer for ProRes removes the first eight bytes. However, a packetizer is not the right place for such a modification, but rather the reader as it's the reader's job to prepare the data for mkvmerge's internal representation.

Think of it this way. When someone implements explicit support in the Matroska reader (instead of relying on the pass-through module) then she couldn't use the packetizer as it is — the data in the Matroska file doesn't contain those eight bytes that the packetizer would try to skip.

**Comment by chenchao1983** [comment]
Thanks for review the changes. The private data of Prores codec is required by the mkv container. Excerpted from [here](https://www.matroska.org/technical/specs/codecid/index.html)
```
The private data contains the fourcc as found in MP4 movies:
apch: ProRes 422 High Quality
apcn: ProRes 422 Standard Definition
apcs: ProRes 422 LT
apco: ProRes 422 Proxy
ap4h: ProRes 4444
```
The frames consist of the same frame as found in MP4, minus the 'Frame container atom' header. See this page for more technical details on ProRes.

I have put the frame container header removal operation into the reader of mov container. Thanks for your comments. I agree with you. Using reader to filter atoms is the correct way to support more codecs.

**Comment by mbunkus** [comment]
Oh, right! We added Prores to the codec specs page back at [the end of 2011](https://lists.matroska.org/pipermail/matroska-devel/2011-December/004144.html). I totally forgot about that.

Your patch looks good to me so far. I'll look for a couple of files to test with later this weekend.

**Comment by mbunkus** [comment]
I've cherry-picked your commit safe for the change to the `libebml` and `libmatroska` sub-modules. I don't know why you've included those; they're actually both going back a single revision.

Thanks again!

**Pull request closed without merging**
