### PR TITLE
add DTS:X bitstream detection

### PR DESCRIPTION
**Pull request by KonaBlend**
DTS:X detection is minimal and only checks for a syncword. There is yet
no released technical spec for a DTS:X header.

This implementation does not scan a range of bytes for the syncword,
rather it first performs more thorough decoding of XLL header necessary
to reliably find the exact syncword position.

Incidental,
sbrm.h provides Scope-Bound Resource Management (SBRM) utilities.

Incidental,
{ format.h, format.cpp } provide boost::format helpers, useful when
producing debug output of tables based on key-value pairs.

### CODE REVIEW

**Comment by KonaBlend** [comment]
1/16 DTS tests fails: T_479dts_7_1_channels

I'm thinking it does the right thing, but not 100% sure.

**Comment by mbunkus** [comment]
Unfortunately your code doesn't compile at the moment with gcc 5.3.0 on Arch Linux with `-std=gnu++14`. Error message:

    In file included from src/common/dts_xll.cpp:21:
    src/common/sbrm.h:150:30: fatal error: no member named 'make_shared' in 'std::shared_ptr<mtx::dts::xll_header_t>'
        this->result = result_t::make_shared();
                                 ^
    src/common/dts_xll.cpp:92:5: note: in instantiation of member function 'mtx::sbrm::result_guard_c<mtx::dts::xll_header_t>::make_result' requested here
      h.make_result();

**Comment by mbunkus** [comment]
Fixing the compilation was easy enough:

    this->result = std::make_shared<T>();

and similar for the version with arguments.

However, the failing test case should really not fail the way it currently does fail. If you run that case once with a clean mkvmerge (meaning one without your patch applied) and once with your modified version you'll see that only a couple of audio frames are actually output with your version, and a lot of frames are simply missing.

Here's how I compared those results (`cleanmkvmerge` is mkvmerge without your patch applied):

    mkdir good bad diff
    cleanmkvmerge -S -D -a 1 -o good/out.mkv ~/data/ts/dts_channel_ext_7_1.m2ts
    mkvmerge -S -D -a 1 -o bad/out.mkv ~/data/ts/dts_channel_ext_7_1.m2ts
    mkvinfo -s good/out.mkv > good/s.txt
    mkvinfo -s bad/out.mkv > bad/s.txt
    diff -u good/s.txt bad/s.txt > diff/s.diff

Then look at s.diff and you'll see what I mean.

Can you please look into this? Thanks.

**Comment by KonaBlend** [comment]
While debugging, I shifted the code to exactly match good-mkvmerge behaviour:
- do not attempt to parse xll if `xll_sync_present == false`
- parse only xll_common header

...and this produces the same `mkvinfo -s` output. So from this good point:
- parse channel_set headers (this file has 2 chsets { 6 channels, 2 channel })

and the 33rd `decode_xll_header` call, things start to go bad. It runs out of data and the chset[0] size looks bogus too.

and the 34th call, chsets[0..1] both have bogus looking sizes, and fail crc16.

I've looked over exss and asset parsing code, couldn't find any issues there. I think simply the XLL data in `dts_channel_ext_7_1.m2ts` is corrupt.

Another potential indicator of corrupt data is, the xll_sync_present goes from true to false several times.

Any thoughts or ideas on what to try next?

**Comment by mbunkus** [comment]
Thanks for the continued work on this. Of course it's possible that the file in question is corrupt. I'll have to look into it on the weekend.

What to try next: I'd say use the code with more samples, e.g. the three listed here: http://kodi.wiki/view/Samples

**Comment by KonaBlend** [comment]
\# prepare z0.dts using mkvtoolnix-9.0.1
\# dredd.m2ts is sample 12 from http://kodi.wiki/view/Samples)
- `mkvmerge -o z0.mkv -D -S dredd.m2ts`
- `mkvextract tracks z0.mkv 0:z0.dts`

After applying *minimal* XLL decoding to master, the 1718th decode_core fails due to the following data occurance:
screen shot 2016-04-10 at 1 16 43 pm

So this is happening:
- decode_core_header() -> decode_exss_header() -> decode_asset() -> decode_xll_header()
- in **master** decode_xll_header() decodes [ 41 a2 95 47 ] successfully because the code only checks for XLL syncword
- in **dtsx** decode_xll_header() decodes [ 41 a2 95 47 ] successfully, then expects a XLL common header, because that's what the spec says, and the next data is not header data, rather it is CORE syncword [ 7f fe 80 01 ]

Diagnosis:
- z0.dts has back-to-back { XLL, CORE } syncwords
- somewhere during creation of `z0.mkv` mkvtoolnix wrote out that sequence
- back-to-back syncwords sequence does **not** occur in `dredd.m2ts`
- this looks to be a bug in mkvtoolnix remuxing; spitting out an extra word in error? truncating XLL data beyond syncword in error?

**Comment by mbunkus** [comment]
I cannot reproduce such corruption. I've downloaded the same file and then created the DTS with different tools: `mkvmerge`/`mkvextract` and `ffmpeg`. The files created in both steps are identical (output cut short on purpose):

    [0 mosu@sweet-chili /ftp/pub/rip/mkv/dts/dtshd/compound] mkvmerge -o mkvmerge.mka -D -S Dredd\ –\ DTS\ Sound\ Check\ DTS-HD\ MA\ 7.1.m2ts
    mkvmerge v9.0.1 ('Obstacles') 64bit
    …
    [0 mosu@sweet-chili /ftp/pub/rip/mkv/dts/dtshd/compound] mkvextract tracks mkvmerge.mka 0:mkvmerge.dts
    Extracting track 0 with the CodecID 'A_DTS' to the file 'mkvmerge.dts'. Container format: Digital Theater System (DTS)
    Progress: 100%
    [0 mosu@sweet-chili /ftp/pub/rip/mkv/dts/dtshd/compound] ffmpeg -i Dredd\ –\ DTS\ Sound\ Check\ DTS-HD\ MA\ 7.1.m2ts -vn -acodec copy ffmpeg.dts
    ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
    …
    Input #0, mpegts, from 'Dredd – DTS Sound Check DTS-HD MA 7.1.m2ts':
    …
        Stream #0:1[0x1100]: Audio: dts (DTS-HD MA) ([134][0][0][0] / 0x0086), 48000 Hz, 7.1, s32p (24 bit)
    [0 mosu@sweet-chili /ftp/pub/rip/mkv/dts/dtshd/compound] cmp mkvmerge.dts ffmpeg.dts
    [0 mosu@sweet-chili /ftp/pub/rip/mkv/dts/dtshd/compound]

However, I can find the XLL syncword [ 41 a2 95 47 ] directly followed by core syncwords [ 7f fe 80 01 ] in both files. If that sequence isn't present in the M2TS file then it's quite possible that the XLL syncword is at the end of a PES packet with the next PES packet starting with the core syncword.

What that means I'm not sure. If this is OK according to the specs (maybe even if it isn't) then mkvmerge's code should probably simply check if an XLL syncword is directly followed by a core syncword and accept that somehow…

Neither mkvmerge nor mkvextract seems to be buggy, though.

**Comment by KonaBlend** [comment]
A search against dredd bitstream yields the following core syncs that are 16 or less bytes from previous xll syncword.

```
SYNC             FILE        hex/decimal/bits                    PREVIOUS SYNC
core 0x7ffe8001  offset root/0xd0ef8/855800/6846400b             xll      -8 bytes
core 0x7ffe8001  offset root/0xdcd1c/904476/7235808b             xll     -16 bytes
core 0x7ffe8001  offset root/0x1869bc/1599932/12799456b          xll      -4 bytes
core 0x7ffe8001  offset root/0x70113c/7344444/58755552b          xll     -16 bytes
core 0x7ffe8001  offset root/0xd86b1c/14183196/113465568b        xll      -4 bytes
core 0x7ffe8001  offset root/0x10fb8c8/17807560/142460480b       xll      -8 bytes
core 0x7ffe8001  offset root/0x112ee34/18017844/144142752b       xll      -8 bytes
core 0x7ffe8001  offset root/0x1210b2c/18942764/151542112b       xll      -4 bytes
core 0x7ffe8001  offset root/0x1269df4/19308020/154464160b       xll      -4 bytes
core 0x7ffe8001  offset root/0x1288cc4/19434692/155477536b       xll     -16 bytes
core 0x7ffe8001  offset root/0x12a07c8/19531720/156253760b       xll      -4 bytes
core 0x7ffe8001  offset root/0x3c1c358/63030104/504240832b       xll      -8 bytes
core 0x7ffe8001  offset root/0x3e1d954/65132884/521063072b       xll      -4 bytes
```

Moving forward on this issue, it looks like you're right, we need to graciously handle these impossible XLL headers. How about this logic:
- succeed if no more data beyond XLL sync; bitcursor moves past XLL sync
- succeed if XLL.header.version != 1; bitcursor moves past XLL sync
- succeed if XLL.header.size < 12 bytes; bitcursor moves past XLL sync
- otherwise parse XLL header and subheaders and navi and optional dtsx as normal, bitcursor moves past parsed headers on success

**Comment by mbunkus** [comment]
Sounds sensible to me.

**Comment by mbunkus** [comment]
Closing this PR due to the project moving to GitLab. This PR has been imported [over there](https://gitlab.com/mbunkus/mkvtoolnix/merge_requests/1629).

**Pull request closed without merging**
