### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by mkver**
This commit deletes some remains of the old GUI.
I am very unsure about this commit so better check it thoroughly. The two messages that I have deleted seem to belong to the old GUI. For example, the window that opens after clicking "Befehlszeile anzeigen" has the title "mkvmerge-Befehlszeile" ("mkvmerge command line", lines 11229 and following) and not "Aktuelle Befehlszeile". That was the title of the corresponding window in the old GUI. 
But simply deleting it might lead to errors: There is no file "src/mkvtoolnix-gui/forms/main_window/main_window.h", but "src/mkvtoolnix-gui/forms/main_window/main_window.ui" exists and contains the string "&amp;Copy command line to clipboard" (by the way: what's the matter with these "&"?). It also refers to an icon edit-copy.png which is only used at this place (and therefore nowhere).
I see that a lot of the translations that are really used refer to the inexisting "src/mkvtoolnix-gui/forms/main_window/main_window.h" so one cannot simply delete all of them. I guess that main_window.h file is created during compilation out of the main_window.ui file, isn't it? So it should  be altered, too (if I am right and these are really unused remains of the old GUI).

### CODE REVIEW

**Comment by mbunkus** [comment]
Thanks, but those messages are all still used. All those `.ui` files are converted to `.h` files during compilation, and the strings to translate are then taken from those newly created `.h` files (that don't exist when you haven't compiled yet). Therefore they cannot be removed.

The `&` character denotes the keyboard accelerator.

**Comment by mkver** [comment]
Are you sure that they are still used? Where is the "aktuelle Befehlszeile"-window?

**Comment by mbunkus** [comment]
That's the default window title of the dialog "Merge" → "Show command line". It can (and currently is) be overwritten by the calling code, that's why you don't see it at the moment. When I extend the GUI to support mkvextract that string will likely be shown. So yes, I'm quite sure.

**Comment by mkver** [comment]
I didn't know that you intend to extend the GUI. My intention in proposing this commit was to notify you that this title is overwritten and should therefore be removed. Sorry for wasting your time.

**Pull request closed without merging**
