### PR TITLE
add explicit pch support

### PR DESCRIPTION
**Pull request by KonaBlend**
- convert gcc to use -include
- add clang support for -include
- new target namespace: pch (invoke task pch:help for more details)
- convert a few troublesome source files from ISO-8859-1 -> UTF-8

### CODE REVIEW

**Comment by KonaBlend** [comment]
- rename rake.d/pch.db.json -> config.pch.json
- treat config.pch.json as transient (not committed to repository)

**Comment by mbunkus** [comment]
clang down to 2:17 from 4:05 (no PCH), gcc down to 2:42 from 4:15 (implicit PCH) / 6:33 (no PCH). Very nice! Thanks for all the work.

The only thing I noticed was that even with `USE_PRECOMPILED_HEADERS = no` the build still rescans (how to reproduce: `configure` normally, build once, edit `build-config` and set `USE_PRECOMPILED_HEADERS=no`, `drake clean` and `drake`). However, this is so fast that I don't really care about it.

Are you planning on doing anything else with this or is it ready to merge?

**Comment by KonaBlend** [comment]
fixed. PCH config load/save/scan honor USE_PRECOMPILED_HEADERS=no
rebased/squashed against master. ready to merge!

**Comment by KonaBlend** [comment]
some build times...

--disable-debug --disable-optimization **--disable-qt**
**OSX 10.10.5** w/ clang -- Apple LLVM version 7.0.2 (clang-700.1.81)
ccache 3.2.4 - ccache.conf: sloppiness = pch_defines,time_macros

pch|ccache|time|%cpu|ccache
---|------|----|----|------
no|no|2:21.23|755%
 ||2.21.23|753%
yes|no|1:25.68|697%
 ||1:26.01|696%
no|yes|2:18.83|740%|seed
 ||28.97|114%|hit
yes|yes|2:26.92|704%|seed
 ||29.52|223%|hit

--disable-debug --disable-optimization **--enable-qt**
**Ubuntu 14.04** w/ gcc -- gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
ccache 3.2.4 - ccache.conf: sloppiness = pch_defines,time_macros

pch|ccache|time|%cpu|ccache
---|------|----|----|------
no|no|7:14.66|385%
 ||7:08.56|390%
yes|no|3:11.34|386%
 ||3:04.97|383%
no|yes|7:29.52|393%|seed
 ||26.81|265%|hit
yes|yes|4:10.69|387%|seed
 ||4:13.70|388%|**miss**

**Comment by mbunkus** [comment]
I've done some more tests this morning with clang 3.7.1 on Arch Linux, `CCACHE_SLOPPINESS=pch_defines,time_macros`, with debugging & Qt, without optimizations. What's interesting is that ccache works fine if I redirect drake's `stdout` and `stderr` to `/dev/null` in both runs, or if I do NOT redirect them in both runs. However, ccache fails if I redirect in the first run but not in the second run. Then ccache shows only cache misses.

Here are the numbers for the "redirect in both runs" case:

    [0 mosu@sweet-chili (master) ~/prog/video/mkvtoolnix] ccache --clear --zero-stats ; drake clean ; time ./drake &> /dev/null ; drake clean ; time ./drake &> /dev/null ; ccache --show-stats                                                  Cleared cache
    Statistics cleared
       CLEAN
    ./drake &> /dev/null  871,10s user 71,51s system 384% cpu 4:04,88 total
       CLEAN
    ./drake &> /dev/null  79,26s user 12,95s system 360% cpu 25,593 total
    cache directory                     /home/mosu/.cache/ccache
    primary config                      /home/mosu/.config/ccache.conf
    secondary config      (readonly)
    cache hit (direct)                   423
    cache hit (preprocessed)              35
    cache miss                           458
    called for link                       18
    files in cache                      1375
    cache size                         495.0 MB
    max cache size                       5.0 GB

Here are the numbers for the "don't redirect in either run" case (with drake's output removed manually):

    [0 mosu@sweet-chili (master) ~/prog/video/mkvtoolnix] ccache --clear --zero-stats ; drake clean ; time ./drake ; drake clean ; time ./drake ; ccache --show-stats
    Cleared cache
    Statistics cleared
    …
    ./drake  870,02s user 65,11s system 385% cpu 4:02,75 total
    …
    ./drake  79,06s user 9,84s system 355% cpu 25,035 total
    cache directory                     /home/mosu/.cache/ccache
    primary config                      /home/mosu/.config/ccache.conf
    secondary config      (readonly)
    cache hit (direct)                   426
    cache hit (preprocessed)              32
    cache miss                           458
    called for link                       18
    files in cache                      1376
    cache size                         495.2 MB
    max cache size                       5.0 GB

And last the case where I redirect in the first run but not in the second run:

    [0 mosu@sweet-chili (master) ~/prog/video/mkvtoolnix] ccache --clear --zero-stats ; drake clean ; time ./drake &> /dev/null ; drake clean ; time ./drake ; ccache --show-stats
    Cleared cache
    Statistics cleared
       CLEAN
    ./drake &> /dev/null  871,38s user 73,00s system 384% cpu 4:05,43 total
    …
    ./drake  862,36s user 50,12s system 385% cpu 3:56,93 total
    cache directory                     /home/mosu/.cache/ccache
    primary config                      /home/mosu/.config/ccache.conf
    secondary config      (readonly)
    cache hit (direct)                     0
    cache hit (preprocessed)               0
    cache miss                           916
    called for link                       18
    files in cache                      2683
    cache size                         989.6 MB
    max cache size                       5.0 GB

Anyway, I'm merging this branch now as it is.

**Comment by mbunkus** [comment]
What's not so nice is that drake now always thinks that all files that use the pre-compiled headers must be updated. Normally invoking `./drake ; ./drake` should only compile everything during the first run and nothing during the second run. With your changes merged to my master both runs compile everything.

This looks like a dependency issue where the pre-compiled header is always updated, and subsequently all object files that depend on the header have to be compiled, too.

**Comment by mbunkus** [comment]
Fixed in revision 95c2edd3293a5f074db1f262f385c473056b3076.

**Comment by KonaBlend** [comment]
Ubuntu 15.10 - build matrix

ccache version 3.2.3
: max_size = 5.0G
: sloppiness = pch_defines,time_macros

gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Ubuntu clang version 3.4.2-13ubuntu2 (tags/RELEASE_34/dot2-final) (based on LLVM 3.4.2)
Ubuntu clang version 3.5.2-2 (tags/RELEASE_352/final) (based on LLVM 3.5.2)
Ubuntu clang version 3.6.2-1 (tags/RELEASE_362/final) (based on LLVM 3.6.2)
Ubuntu clang version 3.7.0-2ubuntu4 (tags/RELEASE_370/final) (based on LLVM 3.7.0)

compiler|pch|ccache|run|time|util
--------|---|------|---|----|----
gcc|nopch|no|0|10:03.614|337.53%
 | | |1|09:56.719|342.79%
 | |yes|0|10:02.800|356.04%
 | | |1|00:27.601|218.61%
 |pch|no|0|04:34.658|317.08%
 | | |1|04:07.072|348.81%
 | |yes|0|05:16.828|340.73%
 | | |1|01:15.875|301.22%
clang-3.4|nopch|no|0|06:17.357|368.95%
 | | |1|06:18.043|370.49%
 | |yes|0|06:15.357|368.11%
 | | |1|00:20.102|230.52%
 |pch|no|0|02:42.543|362.58%
 | | |1|02:42.329|361.64%
 | |yes|0|06:23.454|367.59%
 | | |1|00:28.521|240.00%
clang-3.5|nopch|no|0|06:41.689|368.24%
 | | |1|06:41.804|368.03%
 | |yes|0|06:39.163|366.92%
 | | |1|00:21.311|219.46%
 |pch|no|0|02:56.627|361.54%
 | | |1|02:56.466|362.62%
 | |yes|0|06:47.562|367.56%
 | | |1|00:30.822|228.57%
clang-3.6|nopch|no|0|06:58.933|368.71%
 | | |1|06:57.387|368.59%
 | |yes|0|06:52.467|367.70%
 | | |1|00:22.310|213.62%
 |pch|no|0|03:03.712|363.35%
 | | |1|03:04.211|361.39%
 | |yes|0|07:02.030|366.84%
 | | |1|00:28.750|242.92%
clang-3.7|nopch|no|0|07:05.713|369.93%
 | | |1|07:05.522|370.59%
 | |yes|0|06:59.886|369.77%
 | | |1|00:21.482|238.66%
 |pch|no|0|03:03.347|366.53%
 | | |1|03:04.904|364.65%
 | |yes|0|07:08.805|369.35%
 | | |1|00:28.223|256.67%

**Pull request merged**
