### PR TITLE
Added option to compile static binaries

### PR DESCRIPTION
**Pull request by fthiery**
Add --enable-static flag for static compile support

### CODE REVIEW

**Comment by mbunkus** [comment]
Thanks for the pull request. I'll post a couple of comments inline.

**Comment by fthiery** [comment]
So apart from the lpthread question, it now works; however, would you be interested to integrate the complete static build script or should we bundle it in a separate github repository ?

**Comment by mbunkus** [comment]
Thanks for the improvements. I will be out of town/quite busy over the weekend, so I will probably not find the time to test and merge it before the end of next week, though.

**Comment by mbunkus** [comment]
Merged and added you to AUTHORS and ChangeLog. Thanks.

**Pull request merged**
